package history

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"net/url"
	"reflect"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/hivecommons/dibs/pkg/registry"
	"github.com/hivecommons/dibs/pkg/settle"
)

func fixedNow() time.Time {
	return time.Date(2026, 8, 19, 12, 0, 0, 0, time.UTC)
}

func TestFetchIssueActivityFiltersPRsAndScoresDibsIdeas(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/repos/org/repo/issues" {
			t.Fatalf("unexpected path %s", r.URL.Path)
		}
		if got := r.Header.Get("Authorization"); got != "Bearer test-token" {
			t.Fatalf("Authorization = %q", got)
		}
		_ = json.NewEncoder(w).Encode([]map[string]any{
			{"created_at": "2026-08-18T23:30:00Z", "body": "regular issue"},
			{"created_at": "2026-08-18T01:00:00Z", "body": "pr", "pull_request": map[string]any{"url": "x"}},
			{"created_at": "2026-08-17T09:00:00Z", "body": "idea\n\n" + settle.Footer},
			{"created_at": "2026-07-01T09:00:00Z", "body": "updated old issue"},
		})
	}))
	defer srv.Close()

	b := &Backfiller{BaseURL: srv.URL, Token: "test-token", Client: srv.Client(), Now: fixedNow}
	got, err := b.fetchIssueActivity(context.Background(), "org/repo", windowStart(fixedNow()))
	if err != nil {
		t.Fatalf("fetchIssueActivity: %v", err)
	}
	if got["2026-08-18"].RegularIssuesCreated != 1 || got["2026-08-17"].IdeasFiled != 1 {
		t.Fatalf("buckets = %+v", got)
	}
}

func TestFetchIssueActivityClassifiesHumanIssues(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		_ = json.NewEncoder(w).Encode([]map[string]any{
			{"created_at": "2026-08-18T10:00:00Z", "body": "regular", "user": map[string]string{"login": "alice"}},
			{"created_at": "2026-08-18T11:00:00Z", "body": "automation", "user": map[string]string{"login": "renovate[bot]"}},
			{"created_at": "2026-08-18T12:00:00Z", "body": "idea\n\n" + settle.Footer, "user": map[string]string{"login": "bob"}},
			{"created_at": "2026-08-18T13:00:00Z", "body": "bot idea\n\n" + settle.Footer, "user": map[string]string{"login": "kubestellar-hive[bot]"}},
		})
	}))
	defer srv.Close()

	b := &Backfiller{BaseURL: srv.URL, Client: srv.Client(), Now: fixedNow}
	got, err := b.fetchIssueActivity(context.Background(), "org/repo", windowStart(fixedNow()))
	if err != nil {
		t.Fatalf("fetchIssueActivity: %v", err)
	}
	if got["2026-08-18"].RegularIssuesCreated != 2 || got["2026-08-18"].IdeasFiled != 2 {
		t.Fatalf("formula counts changed: %+v", got["2026-08-18"])
	}
	if got["2026-08-18"].IssuesHuman != 2 {
		t.Fatalf("issuesHuman = %d, want regular human + human Dibs idea", got["2026-08-18"].IssuesHuman)
	}
}

func TestFetchPullActivityClassifiesClankerPRs(t *testing.T) {
	mergedRegular := time.Date(2026, 8, 18, 23, 30, 0, 0, time.UTC)
	mergedClanker := time.Date(2026, 8, 17, 9, 0, 0, 0, time.UTC)
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/repos/org/repo/pulls" {
			t.Fatalf("unexpected path %s", r.URL.Path)
		}
		_ = json.NewEncoder(w).Encode([]map[string]any{
			{"created_at": "2026-08-16T08:00:00Z", "merged_at": mergedRegular, "body": "human PR", "head": map[string]string{"ref": "feature/human"}, "user": map[string]string{"login": "alice"}},
			{"created_at": "2026-08-15T08:00:00Z", "merged_at": mergedClanker, "body": "---\n— hive: agent=quality backend=copilot", "head": map[string]string{"ref": "quality/tests"}, "user": map[string]string{"login": "kubestellar-hive[bot]"}},
			{"created_at": "2026-08-14T08:00:00Z", "merged_at": nil, "body": "— hive: agent=architect backend=copilot", "labels": []map[string]string{{"name": "hold"}}},
			{"created_at": "2026-08-13T08:00:00Z", "merged_at": nil, "body": "deps", "user": map[string]string{"login": "renovate[bot]"}},
		})
	}))
	defer srv.Close()

	b := &Backfiller{BaseURL: srv.URL, Client: srv.Client(), Now: fixedNow}
	got, err := b.fetchPullActivity(context.Background(), "org/repo")
	if err != nil {
		t.Fatalf("fetchPullActivity: %v", err)
	}
	if got["2026-08-18"].RegularPRsMerged != 1 {
		t.Fatalf("regular merge bucket = %+v", got["2026-08-18"])
	}
	if got["2026-08-15"].ClankerPRsCreated != 1 || got["2026-08-17"].ClankerPRsMerged != 1 {
		t.Fatalf("clanker merged buckets = %+v / %+v", got["2026-08-15"], got["2026-08-17"])
	}
	if got["2026-08-14"].ClankerPRsCreated != 1 || got["2026-08-14"].PRsClanker != 1 {
		t.Fatalf("clanker created bucket = %+v", got["2026-08-14"])
	}
}

func TestClankerMarkersAreConfigurableAndConservative(t *testing.T) {
	if isClankerPR(pullActivity{Body: "human discussion mentions clanker"}, clankerMarkers()) {
		t.Fatalf("default markers should not classify bare clanker mentions")
	}

	pr := pullActivity{Body: "Generated by RELAY"}
	if isClankerPR(pr, nil) {
		t.Fatalf("empty markers must not classify")
	}
	if !isClankerPR(pr, []string{"relay"}) {
		t.Fatalf("marker should match body case-insensitively")
	}
	pr.Body = "human"
	pr.Head.Ref = "bots/do-work"
	if !isClankerPR(pr, []string{"bots/"}) {
		t.Fatalf("marker should match branch")
	}
}

func TestBackfillIsIdempotent(t *testing.T) {
	if BackfillVersion != 3 {
		t.Fatalf("BackfillVersion = %d, want 3", BackfillVersion)
	}
	var issuesCalls, pullsCalls int
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/repos/org/repo/issues":
			issuesCalls++
			_ = json.NewEncoder(w).Encode([]map[string]any{{"created_at": "2026-08-18T23:30:00Z", "body": "regular"}})
		case "/repos/org/repo/pulls":
			pullsCalls++
			_ = json.NewEncoder(w).Encode([]map[string]any{{"created_at": "2026-08-17T23:30:00Z", "merged_at": "2026-08-18T23:30:00Z", "body": "human"}})
		default:
			http.NotFound(w, r)
		}
	}))
	defer srv.Close()

	st, err := NewStore(t.TempDir())
	if err != nil {
		t.Fatalf("NewStore: %v", err)
	}
	b := &Backfiller{Store: st, BaseURL: srv.URL, Client: srv.Client(), Now: fixedNow}
	if err := b.Backfill(context.Background(), "org/repo"); err != nil {
		t.Fatalf("first Backfill: %v", err)
	}
	first, ok := st.Get("org/repo")
	if !ok {
		t.Fatalf("missing history after first backfill")
	}
	if err := b.Backfill(context.Background(), "org/repo"); err != nil {
		t.Fatalf("second Backfill: %v", err)
	}
	second, ok := st.Get("org/repo")
	if !ok {
		t.Fatalf("missing history after second backfill")
	}
	if first.Version != BackfillVersion || second.Version != BackfillVersion {
		t.Fatalf("versions = %d/%d, want %d", first.Version, second.Version, BackfillVersion)
	}
	if !reflect.DeepEqual(first.Days, second.Days) {
		t.Fatalf("backfill not idempotent:\nfirst=%+v\nsecond=%+v", first.Days, second.Days)
	}
	if issuesCalls != 2 || pullsCalls != 2 {
		t.Fatalf("calls issues=%d pulls=%d, want 2 each", issuesCalls, pullsCalls)
	}
}

func TestVersionBumpForcesRefresh(t *testing.T) {
	st, err := NewStore(t.TempDir())
	if err != nil {
		t.Fatalf("NewStore: %v", err)
	}
	if err := st.Upsert("org/repo", []DayActivity{{Date: "2026-08-18", MergedPRs: 9}}, fixedNow()); err != nil {
		t.Fatalf("Upsert: %v", err)
	}
	st.mu.Lock()
	h := st.data["org/repo"]
	h.Version = BackfillVersion - 1
	st.data["org/repo"] = h
	st.mu.Unlock()

	var calls int
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		calls++
		switch r.URL.Path {
		case "/repos/org/repo/issues":
			_ = json.NewEncoder(w).Encode([]map[string]any{{"created_at": "2026-08-18T23:30:00Z", "body": "regular"}})
		case "/repos/org/repo/pulls":
			_ = json.NewEncoder(w).Encode([]map[string]any{})
		default:
			http.NotFound(w, r)
		}
	}))
	defer srv.Close()

	b := &Backfiller{Store: st, BaseURL: srv.URL, Client: srv.Client(), Now: fixedNow}
	if !b.needsRefresh("org/repo") {
		t.Fatalf("old version should need refresh")
	}
	if err := b.Backfill(context.Background(), "org/repo"); err != nil {
		t.Fatalf("Backfill: %v", err)
	}
	h, ok := st.Get("org/repo")
	if !ok {
		t.Fatalf("missing refreshed history")
	}
	if h.Version != BackfillVersion || calls != 2 {
		t.Fatalf("version/calls = %d/%d, want %d/2", h.Version, calls, BackfillVersion)
	}
	for _, d := range h.Days {
		if d.Date == "2026-08-18" && (d.RegularIssuesCreated != 1 || d.MergedPRs != 0) {
			t.Fatalf("old history was not replaced by refreshed formula counts: %+v", d)
		}
	}
}

func TestBackfillRateLimitDoesNotPersistPartialIssues(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Retry-After", "60")
		w.WriteHeader(http.StatusForbidden)
	}))
	defer srv.Close()

	st, err := NewStore(t.TempDir())
	if err != nil {
		t.Fatalf("NewStore: %v", err)
	}
	b := &Backfiller{Store: st, BaseURL: srv.URL, Client: srv.Client(), Now: fixedNow}
	if err := b.Backfill(context.Background(), "org/repo"); err == nil {
		t.Fatalf("Backfill rate limit error = nil, want error")
	}
	if _, ok := st.Get("org/repo"); ok {
		t.Fatalf("rate-limited issues should not persist partial history")
	}
}

func TestBackfillRateLimitDoesNotPersistPartialPulls(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/repos/org/repo/issues":
			_ = json.NewEncoder(w).Encode([]map[string]any{{"created_at": "2026-08-18T23:30:00Z", "body": "regular"}})
		case "/repos/org/repo/pulls":
			w.Header().Set("X-RateLimit-Remaining", "0")
			w.WriteHeader(http.StatusForbidden)
		default:
			http.NotFound(w, r)
		}
	}))
	defer srv.Close()

	st, err := NewStore(t.TempDir())
	if err != nil {
		t.Fatalf("NewStore: %v", err)
	}
	b := &Backfiller{Store: st, BaseURL: srv.URL, Client: srv.Client(), Now: fixedNow}
	if err := b.Backfill(context.Background(), "org/repo"); err == nil {
		t.Fatalf("Backfill pull rate limit error = nil, want error")
	}
	if _, ok := st.Get("org/repo"); ok {
		t.Fatalf("rate-limited pulls should not persist partial history")
	}
}

func TestNewBackfillerDefaults(t *testing.T) {
	st, err := NewStore(t.TempDir())
	if err != nil {
		t.Fatalf("NewStore: %v", err)
	}
	b := NewBackfiller(st, "token")
	if b.Store != st || b.Token != "token" {
		t.Fatalf("backfiller dependencies not wired: %+v", b)
	}
	if b.Client == nil || b.Logf == nil {
		t.Fatal("backfiller defaults missing client or logger")
	}
	if b.now().IsZero() {
		t.Fatal("default clock returned zero time")
	}
}

func TestStoreListCopiesAndSorts(t *testing.T) {
	st, err := NewStore(t.TempDir())
	if err != nil {
		t.Fatalf("NewStore: %v", err)
	}
	if err := st.Upsert("z/repo", []DayActivity{{Date: "2026-08-18", MergedPRs: 1}}, fixedNow()); err != nil {
		t.Fatalf("Upsert z/repo: %v", err)
	}
	if err := st.Upsert("a/repo", []DayActivity{{Date: "2026-08-18", MergedPRs: 2}}, fixedNow()); err != nil {
		t.Fatalf("Upsert a/repo: %v", err)
	}
	list := st.List()
	if len(list) != 2 || list[0].RepoID != "a/repo" || list[1].RepoID != "z/repo" {
		t.Fatalf("List not sorted by repo: %+v", list)
	}
	list[0].Days[0].MergedPRs = 99
	got, _ := st.Get("a/repo")
	if got.Days[0].MergedPRs != 2 {
		t.Fatalf("List returned mutable store internals: %+v", got.Days[0])
	}
}

func TestRefreshAsyncRunsOnceAndSkipsFresh(t *testing.T) {
	release := make(chan struct{})
	issueCalls := make(chan string, 4)
	var once sync.Once
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/repos/org/repo/issues":
			issueCalls <- r.URL.RawQuery
			once.Do(func() { <-release })
			_ = json.NewEncoder(w).Encode([]map[string]any{})
		case "/repos/org/repo/pulls":
			_ = json.NewEncoder(w).Encode([]map[string]any{})
		default:
			http.NotFound(w, r)
		}
	}))
	defer srv.Close()

	st, err := NewStore(t.TempDir())
	if err != nil {
		t.Fatalf("NewStore: %v", err)
	}
	b := &Backfiller{Store: st, BaseURL: srv.URL, Client: srv.Client(), Now: fixedNow, Logf: t.Logf}
	repos := []registry.RepoProfile{{RepoID: "org/repo"}}
	b.RefreshAsync(repos)
	select {
	case <-issueCalls:
	case <-time.After(5 * time.Second):
		t.Fatal("first RefreshAsync never started")
	}
	b.RefreshAsync(repos)
	select {
	case q := <-issueCalls:
		t.Fatalf("second RefreshAsync started while first was active: %s", q)
	case <-time.After(50 * time.Millisecond):
	}
	close(release)

	deadline := time.After(5 * time.Second)
	for {
		if h, ok := st.Get("org/repo"); ok && len(h.Days) == windowDays {
			break
		}
		select {
		case <-deadline:
			t.Fatal("RefreshAsync never persisted history")
		case <-time.After(10 * time.Millisecond):
		}
	}
	b.RefreshAsync(repos)
	select {
	case q := <-issueCalls:
		t.Fatalf("fresh history should not refresh again: %s", q)
	case <-time.After(50 * time.Millisecond):
	}
	var nilBackfiller *Backfiller
	nilBackfiller.RefreshAsync(repos)
	(&Backfiller{}).RefreshAsync(repos)
}

func TestFetchMergedPullRequestsFiltersSortsAndAuthenticates(t *testing.T) {
	newer := time.Date(2026, 8, 18, 12, 0, 0, 0, time.UTC)
	older := time.Date(2026, 8, 17, 12, 0, 0, 0, time.UTC)
	var sawAuth, sawVersion string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/repos/org/repo/pulls" {
			t.Fatalf("unexpected path %s", r.URL.Path)
		}
		q, _ := url.ParseQuery(r.URL.RawQuery)
		if q.Get("state") != "closed" || q.Get("sort") != "updated" || q.Get("direction") != "desc" {
			t.Fatalf("unexpected query %s", r.URL.RawQuery)
		}
		sawAuth = r.Header.Get("Authorization")
		sawVersion = r.Header.Get("X-GitHub-Api-Version")
		_ = json.NewEncoder(w).Encode([]map[string]any{
			{"title": "  older merge  ", "merged_at": older, "user": map[string]string{"login": "alice"}},
			{"title": "closed only", "merged_at": nil, "user": map[string]string{"login": "bob"}},
			{"title": "newer merge", "merged_at": newer, "user": map[string]string{"login": "carol"}},
		})
	}))
	defer srv.Close()

	b := &Backfiller{BaseURL: srv.URL, Token: "token", Client: srv.Client(), Now: fixedNow}
	got, err := b.FetchMergedPullRequests(context.Background(), "org/repo")
	if err != nil {
		t.Fatalf("FetchMergedPullRequests: %v", err)
	}
	if sawAuth != "Bearer token" || sawVersion != "2022-11-28" {
		t.Fatalf("headers Authorization=%q X-GitHub-Api-Version=%q", sawAuth, sawVersion)
	}
	if len(got) != 2 {
		t.Fatalf("got %d merged PRs: %+v", len(got), got)
	}
	if got[0].Title != "newer merge" || got[0].Author != "carol" || !got[0].MergedAt.Equal(newer) {
		t.Fatalf("newest PR not first/trimmed: %+v", got[0])
	}
	if got[1].Title != "older merge" || strings.TrimSpace(got[1].Title) != got[1].Title {
		t.Fatalf("older PR not trimmed: %+v", got[1])
	}
}
